<?php

namespace App\Utils;

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Collection;

class Inspirasi
{
    public static function quotes(): Collection
    {
        return collect([
            'Jangan menyerah, setiap langkah kecil membawa kita lebih dekat pada tujuan - Anonim',
            'Bermimpilah setinggi langit, jika engkau jatuh, engkau akan jatuh di antara bintang-bintang - Ir. Soekarno',
            'Kesuksesan bukan akhir, kegagalan bukan kehancuran, yang penting adalah keberanian untuk terus melangkah - Winston Churchill',
            'Setiap hari adalah kesempatan baru untuk menjadi lebih baik dari kemarin - Anonim',
            'Hidup bukan tentang menunggu badai berlalu, tapi belajar menari di tengah hujan - Vivian Greene',
            'Kegagalan hanyalah kesempatan untuk memulai lagi dengan lebih cerdas - Henry Ford',
            'Keberhasilan tidak datang dari apa yang kamu lakukan sesekali, tapi dari apa yang kamu lakukan setiap hari - Anonim',
            'Tidak ada jalan pintas menuju tempat yang berharga - Beverly Sills',
            'Mimpi tidak akan bekerja kecuali kamu bekerja keras untuk mewujudkannya - John C. Maxwell',
            'Sukses dimulai dari keberanian untuk mencoba - Anonim',
            'Keyakinan adalah langkah pertama menuju pencapaian - Anonim',
            'Hidupmu tidak akan berubah jika kamu tidak berubah - Jim Rohn',
            'Keajaiban terjadi ketika kamu tidak menyerah - Anonim',
            'Lakukan yang terbaik, Tuhan akan melakukan sisanya - Anonim',
            'Jangan bandingkan dirimu dengan orang lain, bandingkan dirimu dengan dirimu yang kemarin - Anonim',
            'Setiap kesulitan adalah peluang untuk tumbuh - Anonim',
            'Perjalanan ribuan mil dimulai dari satu langkah - Lao Tzu',
            'Percaya pada dirimu sendiri, karena tidak ada yang bisa melakukannya sebaik kamu - Anonim',
            'Kedisiplinan adalah jembatan antara tujuan dan pencapaian - Jim Rohn',
            'Orang sukses bukanlah orang yang tidak pernah gagal, tapi orang yang tidak pernah menyerah - Anonim',
            'Waktu terus berjalan, gunakanlah sebaik mungkin - Anonim',
            'Pekerjaan besar tidak pernah lahir dari zona nyaman - Anonim',
            'Hargai proses, karena di sanalah karakter terbentuk - Anonim',
            'Setiap tetes keringat hari ini akan menjadi hasil manis esok hari - Anonim',
            'Masa depanmu ditentukan oleh apa yang kamu lakukan hari ini, bukan besok - Anonim',
            'Jika kamu lelah, istirahatlah. Tapi jangan berhenti - Anonim',
            'Hidup adalah tentang keberanian untuk terus melangkah - Anonim',
            'Belajarlah dari masa lalu, hiduplah untuk hari ini, berharaplah untuk esok - Albert Einstein',
            'Masa depan cerah bagi mereka yang mau berusaha - Anonim',
            'Orang hebat tidak lahir dari kenyamanan - Anonim',
            'Semakin besar tantanganmu, semakin besar pula kesempatanmu untuk tumbuh - Anonim',
            'Bangkit bukan berarti tidak pernah jatuh, tapi tidak menyerah saat jatuh - Anonim',
            'Sukses adalah milik mereka yang pantang menyerah - Anonim',
            'Jangan tunggu waktu yang tepat, ciptakan waktu itu sendiri - Anonim',
            'Keberanian bukan berarti tidak takut, tapi melangkah meski takut - Nelson Mandela',
            'Fokus pada tujuanmu, bukan pada hambatan - Anonim',
            'Orang sukses adalah mereka yang bisa tetap tenang saat badai datang - Anonim',
            'Jadikan dirimu versi terbaik setiap harinya - Anonim',
            'Tindakan kecil yang konsisten lebih berarti daripada niat besar tanpa aksi - Anonim',
            'Jika kamu tidak berani mencoba, kamu tidak akan pernah tahu seberapa jauh kamu bisa melangkah - Anonim',
            'Kesuksesan datang saat persiapan bertemu kesempatan - Seneca',
            'Impian tanpa aksi hanya akan menjadi angan-angan - Anonim',
            'Jangan menunggu motivasi datang, bangun motivasimu sendiri - Anonim',
            'Kamu tidak perlu hebat untuk memulai, tapi kamu perlu memulai untuk menjadi hebat - Zig Ziglar',
            'Jangan pernah meremehkan langkah kecil - Anonim',
            'Keberhasilan besar adalah kumpulan dari langkah kecil - Anonim',
            'Lakukan dengan hati, maka hasil tidak akan mengkhianati - Anonim',
            'Hidupmu adalah tanggung jawabmu - Anonim',
            'Jika tidak sekarang, kapan lagi? - Anonim',
            'Berhenti bermimpi, mulailah bertindak - Anonim',
            'Orang sukses mencari cara, orang gagal mencari alasan - Anonim',
            'Hidup bukan soal siapa yang paling cepat, tapi siapa yang tidak pernah berhenti - Anonim',
            'Jangan takut memulai dari bawah, karena semua yang besar berawal dari kecil - Anonim',
            'Bermimpilah setinggi langit, jika engkau jatuh, engkau akan jatuh di antara bintang-bintang - Ir. Soekarno',
            'Perjuanganku lebih mudah karena mengusir penjajah. Perjuanganmu akan lebih sulit karena melawan bangsamu sendiri - Ir. Soekarno',
            'Bangsa yang besar adalah bangsa yang menghargai jasa pahlawannya - Ir. Soekarno',
            'Jangan pernah menyerah, karena dengan keyakinan, semua akan menjadi mungkin - B.J. Habibie',
            'Cintailah pekerjaanmu, maka kamu tidak akan merasa bekerja seumur hidupmu - B.J. Habibie',
            'Kebahagiaan bukanlah tentang seberapa besar kita memiliki, tapi seberapa besar kita mensyukuri - Gus Dur',
            'Hidup itu indah jika kita tidak takut untuk menjalaninya - Gus Dur',
            'Jangan takut bermimpi, karena dari mimpi itulah masa depan dibangun - R.A. Kartini',
            'Habis gelap terbitlah terang - R.A. Kartini',
            'Kita tidak boleh menyerah hanya karena kita perempuan - R.A. Kartini',
            'Tidak ada keberhasilan yang diraih tanpa kerja keras - Jenderal Sudirman',
            'Kebebasan tidak datang begitu saja, ia harus diperjuangkan - Bung Hatta',
            'Kemerdekaan hanyalah jembatan, bukan tujuan akhir - Bung Karno',
            'Belajar tanpa berpikir itu sia-sia, berpikir tanpa belajar itu berbahaya - Confucius (dikutip Bung Hatta)',

            // 📖 Al Qur’an
            'Sesungguhnya bersama kesulitan ada kemudahan - Al Qur’an (QS. Al-Insyirah: 6)',
            'Allah tidak akan mengubah nasib suatu kaum hingga mereka mengubah nasib mereka sendiri - Al Qur’an (QS. Ar-Ra’d: 11)',
            'Dan janganlah kamu berputus asa dari rahmat Allah - Al Qur’an (QS. Yusuf: 87)',
            'Maka sesungguhnya bersama kesulitan ada kemudahan - Al Qur’an (QS. Al-Insyirah: 5)',
            'Karena sesungguhnya sesudah kesulitan itu ada kemudahan - Al Qur’an (QS. Al-Insyirah: 6)',
            'Barang siapa bertakwa kepada Allah niscaya Dia akan membukakan jalan keluar baginya - Al Qur’an (QS. At-Thalaq: 2)',
            'Sesungguhnya Allah bersama orang-orang yang sabar - Al Qur’an (QS. Al-Baqarah: 153)',
            'Ingatlah, hanya dengan mengingat Allah hati menjadi tenteram - Al Qur’an (QS. Ar-Ra’d: 28)',
            'Dan janganlah kamu merasa lemah dan janganlah pula bersedih hati, kamu paling tinggi derajatnya jika kamu beriman - Al Qur’an (QS. Ali Imran: 139)',
            'Maka ingatlah kepada-Ku, niscaya Aku akan mengingatmu - Al Qur’an (QS. Al-Baqarah: 152)',

            // 🕌 Hadits Nabi Muhammad SAW
            'Sebaik-baik manusia adalah yang paling bermanfaat bagi manusia lainnya - Nabi Muhammad SAW (HR. Ahmad)',
            'Orang kuat bukanlah yang pandai bergulat, tapi orang yang mampu mengendalikan diri saat marah - Nabi Muhammad SAW (HR. Bukhari & Muslim)',
            'Barangsiapa bersungguh-sungguh, maka ia akan berhasil - Hadits Nabi',
            'Senyummu kepada saudaramu adalah sedekah - Nabi Muhammad SAW (HR. Tirmidzi)',
            'Sesungguhnya amal itu tergantung pada niatnya - Nabi Muhammad SAW (HR. Bukhari Muslim)',
            'Barangsiapa beriman kepada Allah dan hari akhir, hendaklah ia berkata baik atau diam - Nabi Muhammad SAW (HR. Bukhari & Muslim)',
            'Sesungguhnya Allah tidak melihat rupa dan harta kalian, tetapi Allah melihat hati dan amal kalian - Nabi Muhammad SAW (HR. Muslim)',
            'Permudahlah urusan orang lain, maka Allah akan memudahkan urusanmu - Nabi Muhammad SAW (HR. Muslim)',
            'Orang terbaik di antara kalian adalah yang paling baik akhlaknya - Nabi Muhammad SAW (HR. Tirmidzi)',
            'Orang yang paling dicintai Allah adalah yang paling bermanfaat bagi manusia - Nabi Muhammad SAW (HR. Thabrani)',

            // 🌟 Sahabat Nabi & Ulama
            'Hisablah dirimu sebelum kamu dihisab - Umar bin Khattab',
            'Aku lelah, tapi aku tidak akan menyerah - Umar bin Khattab',
            'Ilmu tanpa amal adalah kegilaan, amal tanpa ilmu adalah kesia-siaan - Imam Al-Ghazali',
            'Jangan terlalu lama bersedih, karena matahari akan tetap terbit esok hari - Ali bin Abi Thalib',
            'Siapa yang bersabar, maka ia akan memperoleh kemenangan - Ali bin Abi Thalib',
            'Nilai seseorang tergantung pada apa yang ia perjuangkan - Ali bin Abi Thalib',
            'Hidup dunia hanya sementara, maka jadikan ia sebagai ladang akhirat - Imam Syafi’i',
            'Bila kau ingin mengenal seseorang, lihatlah siapa temannya - Ali bin Abi Thalib',
            'Jangan terlalu bergantung pada siapa pun di dunia ini, karena bayanganmu saja akan meninggalkanmu saat gelap - Ibnu Qayyim',
            'Ridha Allah terletak pada ridha orang tua, murka Allah terletak pada murka orang tua - Abdullah bin Umar (HR. Tirmidzi)',
        ])->merge(Inspiring::quotes());
    }
}
