import { EventInput } from '@fullcalendar/core';
import { DailyWorkField } from '@/components/logbook/LkhForm.vue';

let eventGuid = 0
let todayStr = new Date().toISOString().replace(/T.*$/, '') // YYYY-MM-DD of today

export const INITIAL_EVENTS: EventInput[] = [
  {
    id: createEventId(),
    title: 'Ini adalah halaman default modul, buat module hebatmu di sini!',
    start: todayStr,
  },
  {
    id: createEventId(),
    title: 'Timed event',
    start: todayStr + 'T12:30:00'
  }
]

export type DailyWorkEvent = Omit<DailyWorkField, 'id'> & { id?: string };

export const DAILY_WORK_FIELDS: DailyWorkEvent[] = [
  {
    id: '21',
    monthly_work_id: 10,
    title: 'Menyusun laporan kegiatan harian pegawai',
    quantity: 3,
    unit: 'Dokumen',
    output: 'Laporan LCKH format PDF',
    start: "2025-10-28",
    evidence_link: 'https://drive.google.com/file/d/abcd1234',
    file: {
      name: 'laporan_lckh.pdf',
      size: '1.2MB',
      type: 'application/pdf',
    },
  },
  {
    id: '22',
    monthly_work_id: 10,
    title: 'Melakukan input data ke sistem e-logbook',
    quantity: 5,
    unit: 'Kegiatan',
    output: 'Data berhasil diinput ke sistem',
    start: "2025-10-28",
    evidence_link: '',
    file: {},
  },
  {
    id: '23',
    monthly_work_id: 11,
    title: 'Membuat dokumentasi penggunaan aplikasi internal',
    quantity: 1,
    unit: 'Dokumen',
    output: 'Panduan pengguna (user manual)',
    start: "2025-10-29",
    evidence_link: 'https://intranet.example.com/docs/user-manual',
    file: {
      name: 'user_manual.docx',
      size: '560KB',
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    },
  },
  {
    id: '24',
    monthly_work_id: 11,
    title: 'Review dan validasi data absensi pegawai',
    quantity: 1,
    unit: 'Laporan',
    output: 'Rekap absensi pegawai bulan ini',
    start: "2025-10-29",
    evidence_link: '',
    file: {},
  },
  {
    id: '25',
    monthly_work_id: 12,
    title: 'Menghadiri rapat koordinasi divisi IT',
    quantity: 1,
    unit: 'Kegiatan',
    output: 'Notulen rapat dan daftar hadir',
    start: "2025-10-29",
    evidence_link: '',
    file: {
      name: 'notulen_rapat.pdf',
      size: '300KB',
      type: 'application/pdf',
    },
  },
  {
    id: '1',
    monthly_work_id: 14,
    title: "Kegiatan harian ke-1",
    quantity: 4,
    unit: "Lainnya",
    output: "Hasil kegiatan ke-1",
    start: "2025-10-30",
    evidence_link: "https://example.com/evidence/1",
    file: null,
  },
  {
    id: '2',
    monthly_work_id: 19,
    title: "Kegiatan harian ke-2",
    quantity: 1,
    unit: "Siswa",
    output: "Hasil kegiatan ke-2",
    start: "2025-10-02",
    evidence_link: "https://example.com/evidence/2",
    file: null,
  },
  {
    id: '3',
    monthly_work_id: 18,
    title: "Kegiatan harian ke-3",
    quantity: 3,
    unit: "Data",
    output: "Hasil kegiatan ke-3",
    start: "2025-10-03",
    evidence_link: "https://example.com/evidence/3",
    file: null,
  },
  {
    id: '4',
    monthly_work_id: 13,
    title: "Kegiatan harian ke-4",
    quantity: 1,
    unit: "Dokumen",
    output: "Hasil kegiatan ke-4",
    start: "2025-10-04",
    evidence_link: "https://example.com/evidence/4",
    file: null,
  },
  {
    id: '5',
    monthly_work_id: 11,
    title: "Kegiatan harian ke-5",
    quantity: 5,
    unit: "File",
    output: "Hasil kegiatan ke-5",
    start: "2025-10-05",
    evidence_link: "https://example.com/evidence/5",
    file: null,
  },
  {
    id: '6',
    monthly_work_id: 12,
    title: "Kegiatan harian ke-6",
    quantity: 2,
    unit: "Kegiatan",
    output: "Hasil kegiatan ke-6",
    start: "2025-10-06",
    evidence_link: "https://example.com/evidence/6",
    file: null,
  },
  {
    id: '7',
    monthly_work_id: 15,
    title: "Kegiatan harian ke-7",
    quantity: 3,
    unit: "Viewer",
    output: "Hasil kegiatan ke-7",
    start: "2025-10-07",
    evidence_link: "https://example.com/evidence/7",
    file: null,
  },
  {
    id: '8',
    monthly_work_id: 17,
    title: "Kegiatan harian ke-8",
    quantity: 2,
    unit: "Pengguna",
    output: "Hasil kegiatan ke-8",
    start: "2025-10-08",
    evidence_link: "https://example.com/evidence/8",
    file: null,
  },
  {
    id: '9',
    monthly_work_id: 20,
    title: "Kegiatan harian ke-9",
    quantity: 4,
    unit: "Dokumen",
    output: "Hasil kegiatan ke-9",
    start: "2025-10-09",
    evidence_link: "https://example.com/evidence/9",
    file: null,
  },
  {
    id: '10',
    monthly_work_id: 10,
    title: "Kegiatan harian ke-10",
    quantity: 5,
    unit: "Laporan",
    output: "Hasil kegiatan ke-10",
    start: "2025-10-10",
    evidence_link: "https://example.com/evidence/10",
    file: null,
  },
  {
    id: '11',
    monthly_work_id: 18,
    title: "Kegiatan harian ke-11",
    quantity: 1,
    unit: "Data",
    output: "Hasil kegiatan ke-11",
    start: "2025-10-12",
    evidence_link: "https://example.com/evidence/11",
    file: null,
  },
  {
    id: '12',
    monthly_work_id: 17,
    title: "Kegiatan harian ke-12",
    quantity: 4,
    unit: "File",
    output: "Hasil kegiatan ke-12",
    start: "2025-10-15",
    evidence_link: "https://example.com/evidence/12",
    file: null,
  },
  {
    id: '13',
    monthly_work_id: 11,
    title: "Kegiatan harian ke-13",
    quantity: 2,
    unit: "Siswa",
    output: "Hasil kegiatan ke-13",
    start: "2025-10-18",
    evidence_link: "https://example.com/evidence/13",
    file: null,
  },
  {
    id: '14',
    monthly_work_id: 13,
    title: "Kegiatan harian ke-14",
    quantity: 5,
    unit: "Laporan",
    output: "Hasil kegiatan ke-14",
    start: "2025-10-21",
    evidence_link: "https://example.com/evidence/14",
    file: null,
  },
  {
    id: '15',
    monthly_work_id: 19,
    title: "Kegiatan harian ke-15",
    quantity: 3,
    unit: "Kegiatan",
    output: "Hasil kegiatan ke-15",
    start: "2025-10-27",
    evidence_link: "https://example.com/evidence/15",
    file: null,
  },
];


export function createEventId() {
  return String(eventGuid++)
}
